session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    sr: sr
    sl: sl
    it: it
  domains:
    en: ''
    sr: ''
    sl: ''
    it: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
